plugins { id 'com.android.application' }

android {
    namespace 'com.vicalox.client'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vicalox.client'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
